# syntax=docker/dockerfile:1
FROM clojure:openjdk-18-tools-deps-buster
RUN \
  apt-get update && \
  apt-get install -y ruby && \
  apt-get install -y nodejs
RUN gem install foreman

WORKDIR /app
CMD clj -J-XX:-OmitStackTraceInFastThrow -A:dev -m audiophile.backend.dev-server $SERVICES
