apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: application
    app: api
  name: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        group: application
    spec:
      containers:
      - name: api
        env:
        - name: MQ_NAMESPACE
          value: k8s
        - name: MQ_CONSUMER_GROUP
          value: api
        - name: MQ_CONSUMER_GLOBAL
          value: "true"
        command: [ "java", "-jar", "target/audiophile.jar", "api" ]
