- op: add
  path: /spec/template/spec/containers/0/image
  value: skuttleman/audiophile:latest
- op: add
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Always
- op: add
  path: /spec/template/spec/imagePullSecrets
  value:
  - name: regcred
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    requests:
      memory: 300Mi
      cpu: 300m
    limits:
      memory: 500Mi
      cpu: 500m
- op: add
  path: /spec/template/spec/containers/0/envFrom
  value:
  - configMapRef:
      name: env-vars
  - secretRef:
      name: env-secrets
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
  - containerPort: 8080
    name: app-port
    protocol: TCP
- op: add
  path: /spec/template/spec/containers/0/readinessProbe
  value:
    httpGet:
      path: /health
      port: app-port
    initialDelaySeconds: 30
    periodSeconds: 10
    failureThreshold: 4
- op: add
  path: /spec/template/spec/containers/0/livenessProbe
  value:
    httpGet:
      path: /health
      port: app-port
    periodSeconds: 10
    failureThreshold: 4
- op: add
  path: /spec/template/spec/containers/0/startupProbe
  value:
    httpGet:
      path: /health
      port: app-port
    initialDelaySeconds: 60
    periodSeconds: 10
    failureThreshold: 10
- op: add
  path: /spec/template/spec/initContainers
  value:
  - name: wait-for-migration
    image: groundnuty/k8s-wait-for:v1.3
    imagePullPolicy: IfNotPresent
    args: [ "job", "job-migrate-db" ]
