apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: application
    app: auth
  name: auth
spec:
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        group: application
    spec:
      containers:
      - name: auth
        command: [ "java", "-jar", "target/audiophile.jar", "auth" ]
