apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: application
    app: jobs
  name: jobs
spec:
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
        group: application
    spec:
      containers:
      - name: jobs
        command: [ "java", "-jar", "target/audiophile.jar", "jobs" ]
        env:
        - name: MQ_NAMESPACE
          value: k8s
        - name: MQ_CONSUMER_GROUP
          value: jobs
