apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    group: application
    app: ui
  name: ui
spec:
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
        group: application
    spec:
      containers:
      - name: ui
        command: [ "java", "-jar", "target/audiophile.jar", "ui" ]
