---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-vol
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-clm
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
