@startuml
hide circle
skinparam linetype ortho

entity "artifacts" as artifacts {
  * id : uuid <<generated>>
  --
  * filename : character varying
  * created_at : timestamp without time zone <<generated>>
  * content_type : character varying
  * key : character varying
  * content_length : integer
  * uri : character varying
}

entity "teams" as teams {
  * id : uuid <<generated>>
  --
  * type : USER-DEFINED
  * created_at : timestamp without time zone <<generated>>
  * name : character varying
}

entity "files" as files {
  * id : uuid <<generated>>
  --
  * project_id : uuid <<FK>>
  * idx : integer
  * name : character varying
  * created_at : timestamp without time zone <<generated>>
}

entity "all_events *VIEW*" as all_events {
  id : uuid
  --
  emitted_by : uuid
  model_id : uuid <<FK>>
  emitted_at : timestamp without time zone
  data : text
  event_type : text
  ctx : jsonb
}

entity "event_types" as event_types {
  * id : uuid <<generated>>
  --
  * category : character varying
  * name : character varying
}

entity "users" as users {
  * id : uuid <<generated>>
  --
  * email : character varying
  * first_name : character varying
  * last_name : character varying
  * created_at : timestamp without time zone <<generated>>
  * handle : character varying
  * mobile_number : character varying
}

entity "file_versions" as file_versions {
  * id : uuid <<generated>>
  --
  * artifact_id : uuid <<FK>>
  * created_at : timestamp without time zone <<generated>>
  * file_id : uuid <<FK>>
  * name : character varying
}

entity "events" as events {
  * id : uuid <<generated>>
  --
  * emitted_at : timestamp without time zone <<generated>>
  ctx : jsonb
  * model_id : uuid <<FK>>
  data : text
  * event_type_id : uuid <<FK>>
  emitted_by : uuid
}

entity "comments" as comments {
  * id : uuid <<generated>>
  --
  * file_version_id : uuid <<FK>>
  comment_id : uuid <<FK>>
  * created_by : uuid
  * created_at : timestamp without time zone <<generated>>
  selection : numrange
  * body : text
}

entity "team_invitations" as team_invitations {
  * created_at : timestamp without time zone <<generated>>
  * team_id : uuid <<FK>>
  * status : USER-DEFINED <<generated>>
  * email : character varying
}

entity "projects" as projects {
  * id : uuid <<generated>>
  --
  * name : character varying
  * team_id : uuid <<FK>>
  * created_at : timestamp without time zone <<generated>>
}

entity "user_teams" as user_teams {
  * team_id : uuid <<FK>>
  * user_id : uuid <<FK>>
}

entity "user_events *VIEW*" as user_events {
  id : uuid
  --
  emitted_at : timestamp without time zone
  event_type : text
  model_id : uuid <<FK>>
  ctx : jsonb
  data : text
  emitted_by : uuid
  user_id : uuid <<FK>>
}

projects ..o files
artifacts ..o file_versions
files ..o file_versions
event_types ..o events
file_versions ..o comments
comments ..o comments
teams ..o team_invitations
teams ..o projects
teams ..o user_teams
users ..o user_teams
users ..o user_events

@enduml
