apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- jobs.yaml
patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
    labelSelector: group=application
