apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patches:
- path: replica-patch.yaml
  target:
    kind: Deployment
    labelSelector: group=application
- path: seed-patch.yaml
  target:
    kind: Deployment
    name: api
